baseURL: http://localhost/
# for xml output
languageCode: "en-au"
# for website
defaultContentLanguage: "en-au"
languages:
  en-au:
    weight: 1
title: Seo Inc.
# alternate copyright company text
copyright: Web Design Inc.
# controls number of pages displayed on list pages
paginate: 6
# controls the summary length on list pages
summaryLength: 7
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
# taxonomy set up (tags have been disabled)
taxonomies:
  category: categories
params:
  slogan: The best in the west

  # https://schema.org/Organization
  ## JSON-LD
  schemaType: "Organization"
    # schemaType: "Person"
  contact:
    # https://schema.org/PostalAddress
    address:
    # first record is for schema
    - name: Address
      streetAddress: 
      - 48 Pirrama Rd
      addressLocality: Pyrmont
      addressRegion: NSW
      postalCode: 2009
      addressCountry: Australia
      # hasMap
      url: https://goo.gl/maps/2bHxJ3bfhtHtnx2b9
      geo: #coordinates 
      # icon: icons/bootstrap/geo-alt.svg
      icon: bi bi-geo-alt
      disable: false
    # postal address is just for contact details display
    # servicePostalAddress:
    #   postOfficeBoxNumber:
    #   addressLocality: Pyrmont
    #   addressRegion: NSW
    #   postalCode: 2009
    #   addressCountry: Australia

    openingHours:
    - name: Opening Hours
      # icon: icons/bootstrap/clock.svg
      icon: bi bi-clock
      hours:
      # date is ignored for display and schema
      - day: Monday
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Tuesday
        open: 2021-01-01T09:00:00
        close: 2021-01-01T17:00:00
      - day: Saturday
        custom: By Appointment
      - day: Sunday
        custom: Closed
    telephone:
    # first record appears in schema data
    - name: Phone
      text: (02) 8004 3293
      url: "tel:+61280043293"
      # icon: icons/bootstrap/phone.svg
      icon: bi bi-phone
      disable: false
    # mobile
    # - text:
    #   url:
    #   icon: icons/bootstrap/telephone
    #   disable: false
    email: 
    - name: Email
      text: test@domain.com
      url: "mailto:test@domain.com"
      # icon: icons/bootstrap/envelope.svg
      icon: bi bi-envelope
      disable: false
      desc: Email Address
  # only for contact details display
    extraItem:
    - name: Help Desk
      text: Help Desk
      url: helpdesk.com
      icon: 
      disable: true


  # founder:
  # foundingDate:
  # foundingLocation:
  # logo
